[project]
name = "sign-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=2.0",
    "pillow>=8.0",
    "pymupdf>=1.18.14",
]
